In [ ]:
import torch
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

In [ ]:
scalar = torch.tensor(7)
scalar

In [ ]:
scalar.ndim

In [ ]:
scalar.item()

In [ ]:
vector = torch.tensor([7,7])
vector

In [ ]:
vector.ndim

In [ ]:
vector.shape

In [ ]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

In [ ]:
MATRIX.ndim

In [ ]:
MATRIX.shape

In [ ]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

In [ ]:
TENSOR.ndim

In [ ]:
TENSOR.shape

In [ ]:
random_tensor = torch.rand(3, 4)
random_tensor

In [ ]:
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

In [ ]:
ones = torch.ones(3,4)
ones

In [ ]:
ones.dtype

In [ ]:
random_tensor.dtype

In [ ]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor, float_32_tensor.dtype

In [ ]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

In [ ]:
float_16_tensor * int_32_tensor

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

In [ ]:
print(some_tensor)
print(f"Datatype: {some_tensor.dtype}")
print(f"Shape: {some_tensor.shape}")
print(f"Device: {some_tensor.device}")

In [ ]:
tensor = torch.tensor([1,2,3])
tensor + 10

In [ ]:
tensor * 10

In [ ]:
tensor - 10

In [ ]:
torch.mul(tensor, 10)

In [ ]:
torch.add(tensor, 10)

In [ ]:
tensor_2 = torch.tensor([2,3,4])
tensor_2

In [ ]:
torch.mul(tensor, tensor_2)

In [ ]:
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

In [ ]:
%%time
torch.matmul(tensor, tensor)

In [ ]:
%%time
value=0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

In [ ]:
torch.matmul(torch.rand(3,5), torch.rand(5,2))

In [ ]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [4,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.mm(tensor_A, tensor_B.T)

In [ ]:
x = torch.arange(1,100,10)
x, x.dtype

In [ ]:
x.min(), x.argmin(), x[0]

In [ ]:
x.max(), x.argmax(), x[9]

In [ ]:
x.type(torch.float32).mean()

In [ ]:
x.sum()

In [ ]:
import torch
x = torch.arange(1.,10.)
x, x.shape

In [ ]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

In [ ]:
z = x.view(1,9)
z, z.shape

In [ ]:
z[:,0] = 5
z, x

In [ ]:
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked, x_stacked.shape

In [ ]:
x_reshaped

In [ ]:
x_reshaped.shape

In [ ]:
x_reshaped.squeeze()

In [ ]:
print(f"prev tns: {x_reshaped}")
print(f"prev shape: {x_reshaped.shape}")
x_squeezed = x_reshaped.squeeze()
print(f"squeezed tns: {x_squeezed}")
print(f"squeezed shape: {x_squeezed.shape}")

In [ ]:
x_unsqueezed = x_squeezed.unsqueeze(0)
print(f"unsqueezed tns: {x_unsqueezed}")
print(f"unsqueezed shape: {x_unsqueezed.shape}")

In [ ]:
x = torch.arange(1.,10.)
x, x.shape

In [ ]:
x = x.unsqueeze(0)
x

In [ ]:
x.permute(1,0)

In [ ]:
x_original = torch.rand(224,224,3)
x_permuted = x_original.permute(2,0,1)

In [ ]:
x_original[0,0,0] = 70540354
x_original[0,0,0], x_permuted[0,0,0]

# Indexing

In [ ]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

In [ ]:
x[0]

In [ ]:
x[0,0]

In [ ]:
x[0,2,2]

In [ ]:
x[:,:,0:3:2]

In [ ]:
x

# PyTorch and NumPy

In [ ]:
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor, tensor.dtype

In [ ]:
array = array+1
array, tensor

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

In [ ]:
tensor = tensor + 1
tensor, numpy_tensor

# Reproducabilty


In [ ]:
import torch
random_tns_A = torch.rand(3,4)
random_tns_B = torch.rand(3,4)
print(random_tns_A)
print(random_tns_B)
print(random_tns_A==random_tns_B)

In [ ]:
import torch

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tns_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tns_D = torch.rand(3,4)

print(random_tns_C)
print(random_tns_D)
print(random_tns_C==random_tns_D)

# GPU Stuff

In [1]:
import torch
torch.cuda.is_available()

False

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [3]:
torch.cuda.device_count()

0

In [4]:
tensor = torch.rand(2)
tensor, tensor.device

(tensor([0.2810, 0.3097]), device(type='cpu'))

In [5]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor.device

(tensor([0.2810, 0.3097]), device(type='cpu'))

In [6]:
tensor_on_cpu = tensor_on_gpu.to("cpu")
tensor_on_cpu, tensor_on_gpu.device

(tensor([0.2810, 0.3097]), device(type='cpu'))